import { ERA0_CHAPTERS } from './Era0Profiles';

export type TruthTag =
  | 'history'
  | 'archaeology'
  | 'myth'
  | 'game-adaptation'
  | 'uncertain'
  | 'tutorial'
  | 'hybrid'
  | 'boss'
  | 'finale';

export type LevelBriefing = {
  era: number;
  level: number;
  title: string;
  chapterLabel: string;
  chapterName: string;
  period: string;
  kind: TruthTag[];
  defenseTargetLabel: string;
  mapIcon?: string;
  shortTeaser: string;
  whyName: string;
  historicalContext: string;
  mythicContext?: string;
  gameAdaptation: string;
  objective: string;
  gameplayTip?: string;
  accuracyNote: string;
};

const chapterMeta = (chapterIndex: number) => {
  const chapter = ERA0_CHAPTERS[chapterIndex];
  const period = chapter.years
    .replace(/~/g, 'c. ')
    .replace(/\s+/g, ' ')
    .replace(/\s*-\s*/g, ' – ')
    .trim();
  return {
    chapterLabel: chapter.label,
    chapterName: chapter.name,
    period,
  };
};

const c1 = chapterMeta(0);
const c2 = chapterMeta(1);
const c3 = chapterMeta(2);
const c4 = chapterMeta(3);

export const ERA0_LEVEL_BRIEFINGS: Record<number, LevelBriefing> = {
  1: {
    era: 0,
    level: 1,
    title: 'The Golden River',
    ...c1,
    kind: ['tutorial', 'history', 'game-adaptation'],
    defenseTargetLabel: 'River village',
    shortTeaser: 'The defense of Sakartvelo begins beside the river that carried gold, trade, and memory toward the sea.',
    whyName: 'The title points to the Rioni River, known in antiquity as the Phasis. The river becomes the symbolic beginning of the Colchian story because it ties together movement, trade, gold traditions, and later mythic memory. This level does not claim one exact battle happened here. It uses the river world as the campaign’s opening ground.',
    historicalContext: 'Before Colchis became famous in Greek storytelling, communities in western Georgia lived among rivers, forests, wetlands, and routes leading to the Black Sea. The Rioni basin linked mountain resources to lowland settlements and coastal exchange. Rivers mattered because they carried food, timber, metals, and people.',
    mythicContext: 'The Golden Fleece belongs to Greek myth, but it became attached to the Colchian world because outsiders imagined this land as wealthy, distant, and dangerous.',
    gameAdaptation: 'The battle, village, and tower-defense structure are fictional gameplay devices inspired by the geography and resource traditions of the Rioni world.',
    objective: 'Learn to move Medea, build your first defenses, and protect the river village.',
    gameplayTip: 'Build near bends in the road so enemies stay in range longer.',
    accuracyNote: 'The Rioni/Phasis setting is historical. Medea as an active battlefield hero and this battle itself are mythic/gameplay adaptation.',
  },
  2: {
    era: 0,
    level: 2,
    title: 'Tribes of the Rioni',
    ...c1,
    kind: ['history', 'game-adaptation'],
    defenseTargetLabel: 'Tribal crossing',
    shortTeaser: 'Before kings and kingdoms, crossings and paths were guarded by local communities.',
    whyName: 'The name points to the early community world before later centralized Colchian power. The Rioni valley was not one palace or one city. It was a network of settlements, crossings, and routes defended locally.',
    historicalContext: 'Before centralized monarchy, communities protected river crossings, forest paths, and trade corridors. Control of movement mattered because whoever held the crossing could protect goods, delay raiders, and organize local defense.',
    gameAdaptation: 'The tower-defense battle is fictional, but its tactical idea represents local defense posts, warning positions, and practical control over movement.',
    objective: 'Hold a crossing and learn how multiple defensive positions support each other.',
    gameplayTip: 'Do not spend all your gold in one spot. Cover the road where enemies turn.',
    accuracyNote: 'The setting is historically plausible. The specific battle is invented for gameplay.',
  },
  3: {
    era: 0,
    level: 3,
    title: "Medea's Grove",
    ...c1,
    kind: ['myth', 'hybrid', 'game-adaptation'],
    defenseTargetLabel: 'Sacred grove',
    shortTeaser: 'The campaign steps from history into myth, where Medea becomes the voice of Colchis.',
    whyName: 'This title marks the campaign’s first strong mythic turn. Medea is not treated here as a verified historical commander. She is a mythic figure associated with Colchis, healing, danger, and hidden knowledge. The grove suggests ritual landscape, herbs, poison, and sacred memory.',
    historicalContext: 'Sacred places, ritual landscapes, and protected gathering spaces were important in many ancient societies. We should not claim this exact grove existed, but the idea of a defended ritual site is historically reasonable.',
    mythicContext: 'Medea belongs to Greek mythic tradition. In the game she becomes a symbolic guide who carries Colchis through the space between history and legend.',
    gameAdaptation: 'Medea’s battlefield magic is fantasy gameplay inspired by mythic associations with herbs, poison, transformation, and ritual power.',
    objective: 'Learn to use Medea’s abilities and survive your first clearly myth-framed defense.',
    gameplayTip: 'Use abilities when enemies cluster together, especially near walls or bends.',
    accuracyNote: 'Medea is mythic. The game uses her as a narrative bridge, not a literal historical record.',
  },
  4: {
    era: 0,
    level: 4,
    title: 'Shores of Pontus',
    ...c1,
    kind: ['history', 'hybrid'],
    defenseTargetLabel: 'Pontus landing',
    shortTeaser: 'The Black Sea brought trade, strangers, wealth, and danger.',
    whyName: '“Pontus” refers to the Black Sea world known to Greek writers. This title shifts the campaign from inland river defense toward the coast, where ships, stories, and threats arrive from beyond the horizon.',
    historicalContext: 'Greek sailors and traders reached the eastern Black Sea and linked local societies to wider exchange networks. Contact could bring wealth and prestige, but also competition and danger.',
    mythicContext: 'The sea is also the route of myth. In the Argonaut story, Jason reaches Colchis by ship in search of the Golden Fleece.',
    gameAdaptation: 'The enemies represent symbolic pressure from the coast, not a reconstruction of one specific documented attack.',
    objective: 'Defend the landing route and adapt to more varied enemy pressure.',
    gameplayTip: 'Spread defenses so one breach does not collapse the whole line.',
    accuracyNote: 'Black Sea contact is historical. The battle itself is fictional.',
  },
  5: {
    era: 0,
    level: 5,
    title: 'Dragon of the Fleece',
    ...c1,
    kind: ['myth', 'boss', 'game-adaptation'],
    defenseTargetLabel: 'Bronze gate',
    shortTeaser: 'Chapter I ends where history gives way to legend: the dragon, the fleece, and the first mythic test.',
    whyName: 'The title comes directly from the Greek myth of the Golden Fleece, where a dragon guards the sacred prize in Colchis. This level is intentionally myth-framed and played as legend rather than documentary history.',
    historicalContext: 'Colchis was associated with wealth, gold, and skilled production. Those associations likely helped Greek storytellers imagine it as the home of the Golden Fleece.',
    mythicContext: 'The dragon and the Golden Fleece belong to mythic literature. They represent guarded treasure, frontier danger, and the idea of Colchis as a wondrous eastern land.',
    gameAdaptation: 'The dragon boss is fantasy gameplay and serves as the chapter-ending boss encounter.',
    objective: 'Defend the mythic threshold and defeat the chapter boss.',
    gameplayTip: 'Prepare before the final wave and use walls and abilities to buy time against the boss.',
    accuracyNote: 'The dragon is myth. Colchian wealth and the region’s link to the Fleece story come from literary tradition.',
  },
  6: {
    era: 0,
    level: 6,
    title: 'Fleece of the Mountain Stream',
    ...c2,
    kind: ['history', 'myth', 'hybrid'],
    defenseTargetLabel: 'Mountain stream',
    shortTeaser: 'The Golden Fleece may echo real memories of gold gathered from mountain waters.',
    whyName: 'The name ties the mythic Golden Fleece to the practical idea of collecting gold from mountain streams. It deliberately sits between real extraction ecology and mythic memory.',
    historicalContext: 'Mountain streams and mineral resources mattered in the western Caucasus. Gold-bearing waters helped shape Colchis’s reputation for wealth.',
    mythicContext: 'The Golden Fleece is myth, but myths can preserve distorted memories of real practices, materials, and places.',
    gameAdaptation: 'The battle is fictional. The stream becomes a defendable resource route because the game turns economic landscapes into tactical spaces.',
    objective: 'Protect the mountain channel and keep the resource route open.',
    gameplayTip: 'Use long-range towers where the path bends around the stream.',
    accuracyNote: 'Gold resources and stream traditions are historical or plausible. The Fleece itself remains mythic.',
  },
  7: {
    era: 0,
    level: 7,
    title: 'Forest Pass of Colchis',
    ...c2,
    kind: ['history', 'game-adaptation'],
    defenseTargetLabel: 'Forest pass',
    shortTeaser: 'In the Caucasus, geography can be stronger than walls.',
    whyName: 'The title points to the forested passes that linked upland and lowland communities. A pass is a natural choke point, and whoever controls it controls movement, warning, and defense.',
    historicalContext: 'Mountain and forest passes shaped life in western Caucasia. Traders, messengers, armies, and raiders all had to move through constrained routes.',
    gameAdaptation: 'The map exaggerates the pass into a tactical lane, but the idea of terrain as defense is historically grounded.',
    objective: 'Hold a narrow route and use chokepoints to your advantage.',
    gameplayTip: 'Walls are strongest when they delay enemies inside tower range.',
    accuracyNote: 'The pass concept is historical and geographical. The exact battle is fictional.',
  },
  8: {
    era: 0,
    level: 8,
    title: 'Colchian Forge Village',
    ...c2,
    kind: ['archaeology', 'history', 'game-adaptation'],
    defenseTargetLabel: 'Forge village',
    shortTeaser: 'Metalwork gave the Colchian world tools, weapons, prestige, and trade value.',
    whyName: 'The title highlights craft production, especially bronze and early iron work. A forge village represents the labor and skill behind weapons, tools, ornaments, and exchange goods.',
    historicalContext: 'Metallurgy was central to ancient societies around the Black Sea and Caucasus. Metalworking supported agriculture, warfare, prestige goods, and long-distance exchange.',
    gameAdaptation: 'The forge village is a symbolic objective, not a claim that this exact settlement existed.',
    objective: 'Protect the workshops that supply the defense.',
    gameplayTip: 'Tougher enemies make upgrades more valuable than spreading too thin.',
    accuracyNote: 'Colchian metalworking is historically important. The battle and exact site are fictional.',
  },
  9: {
    era: 0,
    level: 9,
    title: 'Watchfires of the Caucasus',
    ...c2,
    kind: ['history', 'game-adaptation'],
    defenseTargetLabel: 'Ridge watchfires',
    shortTeaser: 'A warning seen in time can save a valley.',
    whyName: 'The title refers to elevated warning signals across ridges and hills. In mountainous regions, visibility itself can become a defensive tool.',
    historicalContext: 'Mountain societies often relied on terrain, visibility, and warning networks. Even when we cannot document this exact beacon system, the defensive concept is plausible.',
    gameAdaptation: 'The watchfire line is stylized for gameplay and gives a visual identity to a ridge-defense mission.',
    objective: 'Hold the high path and prevent the warning line from falling.',
    gameplayTip: 'Fast enemies are dangerous on long routes, so combine slows, walls, and layered damage.',
    accuracyNote: 'The idea is historically plausible but stylized. Treat it as game adaptation inspired by mountain defense.',
  },
  10: {
    era: 0,
    level: 10,
    title: "Devi Chief's Ravine",
    ...c2,
    kind: ['myth', 'boss', 'hybrid', 'game-adaptation'],
    defenseTargetLabel: 'Ravine gate',
    shortTeaser: 'The first half of the era ends with a monster from Georgian mythic imagination.',
    whyName: 'A devi is a figure from Georgian and Caucasian folklore, often imagined as a giant or monstrous being. The ravine setting frames the creature as a guardian of the wild borderlands.',
    historicalContext: 'This level is not documentary history. It belongs to the campaign’s mythic layer.',
    mythicContext: 'Devi figures come from folklore rather than written battle records. They represent danger, wilderness, and the unknown.',
    gameAdaptation: 'The devi chief is a boss encounter that uses folklore as a fantasy challenge while the campaign’s broader frame remains historical.',
    objective: 'Defend the ravine and defeat the mythic boss.',
    gameplayTip: 'Prepare burst damage and defensive delay before the boss wave begins.',
    accuracyNote: 'The devi is folklore and myth. The battle is fantasy gameplay.',
  },
  11: {
    era: 0,
    level: 11,
    title: 'Phasis Trade Road',
    ...c3,
    kind: ['history'],
    defenseTargetLabel: 'Trade road',
    shortTeaser: 'The Phasis was not only a river. It was a route into the Colchian world.',
    whyName: 'The title connects the ancient name Phasis with movement, commerce, and outside knowledge of Colchis. Roads and river routes carried goods, stories, and political influence.',
    historicalContext: 'Greek geographical and literary traditions remembered Phasis as a major marker of the eastern Black Sea world. Trade and movement shaped how outsiders understood Colchis.',
    mythicContext: 'The same routes that carried trade also carried stories, including the Argonaut myth.',
    gameAdaptation: 'The road is simplified into a battle lane. The level turns logistics into defense.',
    objective: 'Protect the trade corridor from enemy pressure.',
    gameplayTip: 'Build near the longest visible stretch of road to maximize tower uptime.',
    accuracyNote: 'The Phasis/Rioni corridor is historical. The battle is fictional.',
  },
  12: {
    era: 0,
    level: 12,
    title: 'Sacred Oak Clearing',
    ...c3,
    kind: ['history', 'myth', 'hybrid'],
    defenseTargetLabel: 'Sacred clearing',
    shortTeaser: 'A sacred place is not just spiritual. It can hold a community together.',
    whyName: 'The title suggests a ritual landscape centered on a powerful tree. It is meant to evoke pre-Christian sacred space without claiming this exact oak or clearing existed.',
    historicalContext: 'Sacred trees, groves, and ritual landscapes are common across many ancient cultures, including traditions of the Caucasus. Such places can function as gathering points and sources of identity.',
    mythicContext: 'Trees and groves naturally belong to mythic storytelling as places where spirits, ritual, and heroic memory enter the story.',
    gameAdaptation: 'The clearing is a symbolic protected site designed to give the level emotional meaning inside the campaign.',
    objective: 'Protect the sacred clearing and survive heavier pressure.',
    gameplayTip: 'Do not build only at the entrance. Prepare a second defensive line.',
    accuracyNote: 'The general ritual concept is plausible. The specific site is fictional.',
  },
  13: {
    era: 0,
    level: 13,
    title: 'Black Sea Cliffs',
    ...c3,
    kind: ['history'],
    defenseTargetLabel: 'Coastal cliffs',
    shortTeaser: 'The sea opens the world, but cliffs decide where that world can enter.',
    whyName: 'The title emphasizes the rugged eastern Black Sea coastline. Cliffs, inlets, and landing points shape how people arrive, trade, raid, or defend.',
    historicalContext: 'Coastal geography mattered deeply for Black Sea contact. The sea connected Colchis to Greek traders and wider networks, but geography controlled access.',
    mythicContext: 'The sea also carries the Argonaut story toward Colchis.',
    gameAdaptation: 'The level turns a coastal landscape into a controlled defensive route.',
    objective: 'Defend the cliff road and prevent enemies from reaching the interior.',
    gameplayTip: 'Keep flexible coverage because fast or unusual enemies can break simple plans.',
    accuracyNote: 'The coastal setting is historical and geographical. The specific conflict is fictional.',
  },
  14: {
    era: 0,
    level: 14,
    title: "Aeetes' Boundary Stones",
    ...c3,
    kind: ['myth', 'hybrid', 'game-adaptation'],
    defenseTargetLabel: 'Boundary stones',
    shortTeaser: 'At the edge of kingly power, myth gives the land a name and a ruler.',
    whyName: 'Aeetes is the mythic king of Colchis in the Argonaut tradition. Boundary stones suggest rule, territory, and ritual authority. The title is intentionally mythic and uses a legendary king to frame a border defense.',
    historicalContext: 'Territory, boundaries, and authority were real concerns in ancient societies, but these specific stones are not documented historical objects.',
    mythicContext: 'Aeetes belongs to mythic literary tradition. His presence signals that the campaign is moving deeper into the world of the Golden Fleece story.',
    gameAdaptation: 'The stones are a gameplay objective and visual symbol rather than archaeological fact.',
    objective: 'Hold the border markers and prevent the enemy from breaking through.',
    gameplayTip: 'Build in layers so a second line still works if the first line fails.',
    accuracyNote: 'Aeetes is mythic. Boundary defense is a gameplay adaptation inspired by real concerns with land and authority.',
  },
  15: {
    era: 0,
    level: 15,
    title: 'Shrine of the Dragon',
    ...c3,
    kind: ['myth', 'boss', 'game-adaptation'],
    defenseTargetLabel: 'Dragon shrine',
    shortTeaser: 'The dragon returns as a symbol of guarded wealth, fear, and mythic memory.',
    whyName: 'The title expands the dragon motif from the Golden Fleece story into a sacred or mythic place. A shrine suggests that the dragon is not only a monster, but a remembered symbol of awe and fear.',
    historicalContext: 'This is not a historical shrine reconstruction. It belongs to the campaign’s mythic layer.',
    mythicContext: 'The dragon guarding the Golden Fleece is one of the central images of the Colchis myth cycle.',
    gameAdaptation: 'The shrine is a fantasy battlefield built around a chapter-ending boss encounter.',
    objective: 'Defend the shrine path and survive the dragon’s pressure.',
    gameplayTip: 'Use every delay tool available. Boss levels punish weak early preparation.',
    accuracyNote: 'The dragon and shrine are mythic/gameplay inventions rather than historical claims.',
  },
  16: {
    era: 0,
    level: 16,
    title: 'Warrior Trial Grounds',
    ...c4,
    kind: ['history', 'hybrid'],
    defenseTargetLabel: 'Late Colchian stronghold',
    shortTeaser: 'As outside powers grow stronger, Colchis survives through terrain, discipline, and layered defense.',
    whyName: 'The title evokes a proving ground where local fighters prepare for the hardest stage of the era. It fits the late-Colchian mood of resilience under pressure and turns disciplined defense into the map’s identity.',
    historicalContext: 'Late Colchian polities survived through terrain use, fortified nodes, and adaptive alliances as larger powers competed around the Black Sea and Caucasus. Defense depth mattered as much as open battle.',
    gameAdaptation: 'This mission is fictional, but it is designed to feel like a late-era tactical test of everything the defender has learned.',
    objective: 'Hold the stronghold route and protect the remaining heartland approach.',
    gameplayTip: 'Expect stronger mixed waves and build specialized defenses instead of generic coverage.',
    accuracyNote: 'The political pressure is historical in broad terms. The battle is fictional.',
  },
  17: {
    era: 0,
    level: 17,
    title: 'Rioni Marshlands',
    ...c4,
    kind: ['history'],
    defenseTargetLabel: 'Marsh route',
    shortTeaser: 'The marsh itself becomes a defender.',
    whyName: 'The title connects the level to the Rioni wetland world, where marshes and channels shape movement as much as roads do. The place name makes the terrain itself the story.',
    historicalContext: 'Wetlands and marshes can limit movement, slow attackers, and protect settlements. The Rioni system’s geography shaped routes and defensive choices in the western lowlands.',
    gameAdaptation: 'The mission turns marshland into a tactical identity and uses constrained terrain as part of the challenge.',
    objective: 'Use the terrain to hold back enemy movement across the wetlands.',
    gameplayTip: 'Slow enemies even more where the map already constrains them.',
    accuracyNote: 'The geography is plausible and historical. The exact mission is invented.',
  },
  18: {
    era: 0,
    level: 18,
    title: 'Ancient Palisade',
    ...c4,
    kind: ['history', 'game-adaptation'],
    defenseTargetLabel: 'Palisade gate',
    shortTeaser: 'In a timber-rich land, defense can be built from the forest itself.',
    whyName: 'The title frames the level around practical fortification: timber, barriers, and defensive lines built from what the landscape provides. It makes the palisade itself the central character of the map.',
    historicalContext: 'Wooden fortifications, barriers, and prepared defensive positions are plausible in forested regions. Timber-rich environments support practical defensive construction.',
    gameAdaptation: 'The tower-defense wall system exaggerates real defensive delay into a clear and readable game mechanic.',
    objective: 'Hold layered defenses and prevent a breakthrough at the fortified line.',
    gameplayTip: 'Walls are not permanent solutions. They buy time for damage and control.',
    accuracyNote: 'Palisade logic is plausible. The specific scenario is fictional.',
  },
  19: {
    era: 0,
    level: 19,
    title: 'Gate of the Golden Fleece',
    ...c4,
    kind: ['myth', 'hybrid', 'game-adaptation'],
    defenseTargetLabel: 'Fleece gate',
    shortTeaser: 'Before the final collapse, the campaign passes through the symbolic gate of the Golden Fleece.',
    whyName: 'The title treats the Fleece as a threshold between wealth, legend, and political power. The gate is not a documented monument. It is a symbolic campaign space where myth and late-Colchian pressure meet.',
    historicalContext: 'This stage connects the late pressure on Colchis to the symbolic authority of wealth, territory, and remembered prestige.',
    mythicContext: 'The Golden Fleece is myth. In the campaign, it becomes a symbol of what outsiders wanted, imagined, and feared about Colchis.',
    gameAdaptation: 'The gate is campaign lore rather than archaeology. It exists to give the penultimate level a ritual and narrative threshold.',
    objective: 'Defend the threshold before the final Era 0 stand.',
    gameplayTip: 'Treat this as a penultimate test and use every learned mechanic together.',
    accuracyNote: 'The Fleece gate is symbolic fiction. The surrounding historical pressure is real in broad terms.',
  },
  20: {
    era: 0,
    level: 20,
    title: 'Heart of Colchis',
    ...c4,
    kind: ['history', 'finale', 'game-adaptation'],
    defenseTargetLabel: 'Last heart of Colchis',
    shortTeaser: 'Political control changes, but memory survives.',
    whyName: 'The title presents the finale as the defense of what remains essential: not a kingdom saved forever, but a cultural heart carried forward through loss, pressure, and endurance.',
    historicalContext: 'By 83 BC, Colchis had fallen under Pontic control associated with Mithridates VI. That marks the end of the era’s independent political arc, but not the end of local people, language, or memory.',
    mythicContext: 'When mythic elements appear in the finale, they represent memory and legend layered over a real historical transition.',
    gameAdaptation: 'The final battle is fictional. It dramatizes political transition and survival rather than reconstructing one recorded event.',
    objective: 'Survive the final Era 0 battle and complete Ancient Colchis.',
    gameplayTip: 'Use everything: walls, upgrades, Medea’s abilities, and layered defenses.',
    accuracyNote: 'The 83 BC political transition is historical framing. The battle itself is game fiction.',
  },
};
